use std::{io::Write, option_env};

use syn::parse_quote;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let prefix = option_env!("PREFIX").unwrap_or("/usr/local").to_owned();
    let bindir = option_env!("BINDIR")
        .map(ToOwned::to_owned)
        .unwrap_or_else(|| format!("{prefix}/bin"));
    let datadir = option_env!("DATADIR")
        .map(ToOwned::to_owned)
        .unwrap_or_else(|| format!("{prefix}/share"));
    let pkgdatadir = option_env!("PKGDATADIR")
        .map(ToOwned::to_owned)
        .unwrap_or_else(|| format!("{datadir}/xfce4/xfwl4"));
    let localedir = option_env!("LOCALEDIR")
        .map(ToOwned::to_owned)
        .unwrap_or_else(|| format!("{datadir}/locale"));

    let xfwm4_pkgdatadir = option_env!("XFWM4_PKGDATADIR")
        .map(ToOwned::to_owned)
        .unwrap_or_else(|| format!("{datadir}/xfwm4"));

    let gettext_package = env!("CARGO_PKG_NAME");

    let build_config_contents: syn::File = parse_quote! {
        /// This file is autogenerated by build.rs; DO NOT EDIT

        #[allow(unused)]
        pub const BUILD_PREFIX: &str = #prefix;
        #[allow(unused)]
        pub const BUILD_BINDIR: &str = #bindir;
        #[allow(unused)]
        pub const BUILD_DATADIR: &str = #datadir;
        #[allow(unused)]
        pub const BUILD_PKGDATADIR: &str = #pkgdatadir;
        #[allow(unused)]
        pub const BUILD_LOCALEDIR: &str = #localedir;
        #[allow(unused)]
        pub const BUILD_XFWM4_PKGDATADIR: &str = #xfwm4_pkgdatadir;

        #[allow(unused)]
        pub const GETTEXT_PACKAGE: &str = #gettext_package;
    };

    let mut build_config = tempfile::NamedTempFile::new_in(std::env::var("OUT_DIR").expect("OUT_DIR not set"))?;
    build_config.write_all(prettyplease::unparse(&build_config_contents).as_bytes())?;

    let build_config_path = format!(
        "{}/src/build_config.rs",
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set")
    );
    build_config.persist(build_config_path)?;

    Ok(())
}
