// xfwl4 -- Wayland compositor for the Xfce Desktop Environment
//
// Copyright (C) 2026 Brian Tarricone <brian@tarricone.org>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

use std::{fmt, str::FromStr};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum KeyboardShortcutAction {
    WmAction(KeyboardShortcutName),
    Command(String),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum KeyboardShortcutName {
    Cancel,
    Down,
    Left,
    Right,
    Up,
    AddWorkspace,
    AddAdjacentWorkspace,
    CloseWindow,
    CycleWindows,
    CycleReverseWindows,
    DelWorkspace,
    DelActiveWorkspace,
    DownWorkspace,
    FillHoriz,
    FillVert,
    FillWindow,
    HideWindow,
    LeftWorkspace,
    LowerWindow,
    Move,
    MaximizeHoriz,
    MaximizeVert,
    MaximizeWindow,
    MoveToMonitorDown,
    MoveToMonitorLeft,
    MoveToMonitorRight,
    MoveToMonitorUp,
    MoveDownWorkspace,
    MoveLeftWorkspace,
    MoveNextWorkspace,
    MovePrevWorkspace,
    MoveRightWorkspace,
    MoveUpWorkspace,
    NextWorkspace,
    PopupMenu,
    PrevWorkspace,
    RaiseWindow,
    RaiseLowerWindow,
    Resize,
    RightWorkspace,
    ShadeWindow,
    ShowDesktop,
    StickWindow,
    SwitchApplication,
    SwitchWindow,
    TileDown,
    TileLeft,
    TileRight,
    TileUp,
    TileDownLeft,
    TileDownRight,
    TileUpLeft,
    TileUpRight,
    ToggleAbove,
    ToggleFullscreen,
    UpWorkspace,
    MoveWorkspace1,
    MoveWorkspace2,
    MoveWorkspace3,
    MoveWorkspace4,
    MoveWorkspace5,
    MoveWorkspace6,
    MoveWorkspace7,
    MoveWorkspace8,
    MoveWorkspace9,
    MoveWorkspace10,
    MoveWorkspace11,
    MoveWorkspace12,
    Workspace1,
    Workspace2,
    Workspace3,
    Workspace4,
    Workspace5,
    Workspace6,
    Workspace7,
    Workspace8,
    Workspace9,
    Workspace10,
    Workspace11,
    Workspace12,
}

impl KeyboardShortcutName {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Cancel => "cancel_key",
            Self::Down => "down_key",
            Self::Left => "left_key",
            Self::Right => "right_key",
            Self::Up => "up_key",
            Self::AddWorkspace => "add_workspace_key",
            Self::AddAdjacentWorkspace => "add_adjacent_workspace_key",
            Self::CloseWindow => "close_window_key",
            Self::CycleWindows => "cycle_windows_key",
            Self::CycleReverseWindows => "cycle_reverse_windows_key",
            Self::DelWorkspace => "del_workspace_key",
            Self::DelActiveWorkspace => "del_active_workspace_key",
            Self::DownWorkspace => "down_workspace_key",
            Self::FillHoriz => "fill_horiz_key",
            Self::FillVert => "fill_vert_key",
            Self::FillWindow => "fill_window_key",
            Self::HideWindow => "hide_window_key",
            Self::LeftWorkspace => "left_workspace_key",
            Self::LowerWindow => "lower_window_key",
            Self::Move => "move_window_key",
            Self::MaximizeHoriz => "maximize_horiz_key",
            Self::MaximizeVert => "maximize_vert_key",
            Self::MaximizeWindow => "maximize_window_key",
            Self::MoveToMonitorDown => "move_window_to_monitor_down_key",
            Self::MoveToMonitorLeft => "move_window_to_monitor_left_key",
            Self::MoveToMonitorRight => "move_window_to_monitor_right_key",
            Self::MoveToMonitorUp => "move_window_to_monitor_up_key",
            Self::MoveDownWorkspace => "move_window_down_workspace_key",
            Self::MoveLeftWorkspace => "move_window_left_workspace_key",
            Self::MoveNextWorkspace => "move_window_next_workspace_key",
            Self::MovePrevWorkspace => "move_window_prev_workspace_key",
            Self::MoveRightWorkspace => "move_window_right_workspace_key",
            Self::MoveUpWorkspace => "move_window_up_workspace_key",
            Self::NextWorkspace => "next_workspace_key",
            Self::PopupMenu => "popup_menu_key",
            Self::PrevWorkspace => "prev_workspace_key",
            Self::RaiseWindow => "raise_window_key",
            Self::RaiseLowerWindow => "raiselower_window_key",
            Self::Resize => "resize_window_key",
            Self::RightWorkspace => "right_workspace_key",
            Self::ShadeWindow => "shade_window_key",
            Self::ShowDesktop => "show_desktop_key",
            Self::StickWindow => "stick_window_key",
            Self::SwitchApplication => "switch_application_key",
            Self::SwitchWindow => "switch_window_key",
            Self::TileDown => "tile_down_key",
            Self::TileLeft => "tile_left_key",
            Self::TileRight => "tile_right_key",
            Self::TileUp => "tile_up_key",
            Self::TileDownLeft => "tile_down_left_key",
            Self::TileDownRight => "tile_down_right_key",
            Self::TileUpLeft => "tile_up_left_key",
            Self::TileUpRight => "tile_up_right_key",
            Self::ToggleAbove => "above_key",
            Self::ToggleFullscreen => "fullscreen_key",
            Self::UpWorkspace => "up_workspace_key",
            Self::MoveWorkspace1 => "move_window_workspace_1_key",
            Self::MoveWorkspace2 => "move_window_workspace_2_key",
            Self::MoveWorkspace3 => "move_window_workspace_3_key",
            Self::MoveWorkspace4 => "move_window_workspace_4_key",
            Self::MoveWorkspace5 => "move_window_workspace_5_key",
            Self::MoveWorkspace6 => "move_window_workspace_6_key",
            Self::MoveWorkspace7 => "move_window_workspace_7_key",
            Self::MoveWorkspace8 => "move_window_workspace_8_key",
            Self::MoveWorkspace9 => "move_window_workspace_9_key",
            Self::MoveWorkspace10 => "move_window_workspace_10_key",
            Self::MoveWorkspace11 => "move_window_workspace_11_key",
            Self::MoveWorkspace12 => "move_window_workspace_12_key",
            Self::Workspace1 => "workspace_1_key",
            Self::Workspace2 => "workspace_2_key",
            Self::Workspace3 => "workspace_3_key",
            Self::Workspace4 => "workspace_4_key",
            Self::Workspace5 => "workspace_5_key",
            Self::Workspace6 => "workspace_6_key",
            Self::Workspace7 => "workspace_7_key",
            Self::Workspace8 => "workspace_8_key",
            Self::Workspace9 => "workspace_9_key",
            Self::Workspace10 => "workspace_10_key",
            Self::Workspace11 => "workspace_11_key",
            Self::Workspace12 => "workspace_12_key",
        }
    }
}

impl fmt::Display for KeyboardShortcutName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl FromStr for KeyboardShortcutName {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "cancel_key" => Ok(Self::Cancel),
            "down_key" => Ok(Self::Down),
            "left_key" => Ok(Self::Left),
            "right_key" => Ok(Self::Right),
            "up_key" => Ok(Self::Up),
            "add_workspace_key" => Ok(Self::AddWorkspace),
            "add_adjacent_workspace_key" => Ok(Self::AddAdjacentWorkspace),
            "close_window_key" => Ok(Self::CloseWindow),
            "cycle_windows_key" => Ok(Self::CycleWindows),
            "cycle_reverse_windows_key" => Ok(Self::CycleReverseWindows),
            "del_workspace_key" => Ok(Self::DelWorkspace),
            "del_active_workspace_key" => Ok(Self::DelActiveWorkspace),
            "down_workspace_key" => Ok(Self::DownWorkspace),
            "fill_horiz_key" => Ok(Self::FillHoriz),
            "fill_vert_key" => Ok(Self::FillVert),
            "fill_window_key" => Ok(Self::FillWindow),
            "hide_window_key" => Ok(Self::HideWindow),
            "left_workspace_key" => Ok(Self::LeftWorkspace),
            "lower_window_key" => Ok(Self::LowerWindow),
            "move_window_key" => Ok(Self::Move),
            "maximize_horiz_key" => Ok(Self::MaximizeHoriz),
            "maximize_vert_key" => Ok(Self::MaximizeVert),
            "maximize_window_key" => Ok(Self::MaximizeWindow),
            "move_window_to_monitor_down_key" => Ok(Self::MoveToMonitorDown),
            "move_window_to_monitor_left_key" => Ok(Self::MoveToMonitorLeft),
            "move_window_to_monitor_right_key" => Ok(Self::MoveToMonitorRight),
            "move_window_to_monitor_up_key" => Ok(Self::MoveToMonitorUp),
            "move_window_down_workspace_key" => Ok(Self::MoveDownWorkspace),
            "move_window_left_workspace_key" => Ok(Self::MoveLeftWorkspace),
            "move_window_next_workspace_key" => Ok(Self::MoveNextWorkspace),
            "move_window_prev_workspace_key" => Ok(Self::MovePrevWorkspace),
            "move_window_right_workspace_key" => Ok(Self::MoveRightWorkspace),
            "move_window_up_workspace_key" => Ok(Self::MoveUpWorkspace),
            "next_workspace_key" => Ok(Self::NextWorkspace),
            "popup_menu_key" => Ok(Self::PopupMenu),
            "prev_workspace_key" => Ok(Self::PrevWorkspace),
            "raise_window_key" => Ok(Self::RaiseWindow),
            "raiselower_window_key" => Ok(Self::RaiseLowerWindow),
            "resize_window_key" => Ok(Self::Resize),
            "right_workspace_key" => Ok(Self::RightWorkspace),
            "shade_window_key" => Ok(Self::ShadeWindow),
            "show_desktop_key" => Ok(Self::ShowDesktop),
            "stick_window_key" => Ok(Self::StickWindow),
            "switch_application_key" => Ok(Self::SwitchApplication),
            "switch_window_key" => Ok(Self::SwitchWindow),
            "tile_down_key" => Ok(Self::TileDown),
            "tile_left_key" => Ok(Self::TileLeft),
            "tile_right_key" => Ok(Self::TileRight),
            "tile_up_key" => Ok(Self::TileUp),
            "tile_down_left_key" => Ok(Self::TileDownLeft),
            "tile_down_right_key" => Ok(Self::TileDownRight),
            "tile_up_left_key" => Ok(Self::TileUpLeft),
            "tile_up_right_key" => Ok(Self::TileUpRight),
            "above_key" => Ok(Self::ToggleAbove),
            "fullscreen_key" => Ok(Self::ToggleFullscreen),
            "up_workspace_key" => Ok(Self::UpWorkspace),
            "move_window_workspace_1_key" => Ok(Self::MoveWorkspace1),
            "move_window_workspace_2_key" => Ok(Self::MoveWorkspace2),
            "move_window_workspace_3_key" => Ok(Self::MoveWorkspace3),
            "move_window_workspace_4_key" => Ok(Self::MoveWorkspace4),
            "move_window_workspace_5_key" => Ok(Self::MoveWorkspace5),
            "move_window_workspace_6_key" => Ok(Self::MoveWorkspace6),
            "move_window_workspace_7_key" => Ok(Self::MoveWorkspace7),
            "move_window_workspace_8_key" => Ok(Self::MoveWorkspace8),
            "move_window_workspace_9_key" => Ok(Self::MoveWorkspace9),
            "move_window_workspace_10_key" => Ok(Self::MoveWorkspace10),
            "move_window_workspace_11_key" => Ok(Self::MoveWorkspace11),
            "move_window_workspace_12_key" => Ok(Self::MoveWorkspace12),
            "workspace_1_key" => Ok(Self::Workspace1),
            "workspace_2_key" => Ok(Self::Workspace2),
            "workspace_3_key" => Ok(Self::Workspace3),
            "workspace_4_key" => Ok(Self::Workspace4),
            "workspace_5_key" => Ok(Self::Workspace5),
            "workspace_6_key" => Ok(Self::Workspace6),
            "workspace_7_key" => Ok(Self::Workspace7),
            "workspace_8_key" => Ok(Self::Workspace8),
            "workspace_9_key" => Ok(Self::Workspace9),
            "workspace_10_key" => Ok(Self::Workspace10),
            "workspace_11_key" => Ok(Self::Workspace11),
            "workspace_12_key" => Ok(Self::Workspace12),
            unknown => Err(anyhow::anyhow!("unknown keyboard shortcut name: {unknown}")),
        }
    }
}
